1.1

SELECT Nombre FROM ARTICULOS;

1.2

SELECT Nombre, Precio FROM ARTICULOS;

1.3

SELECT Nombre FROM ARTICULOS WHERE Precio > 200;

1.4

SELECT * FROM ARTICULOS WHERE Precio <= 120;
SELECT * FROM ARTICULOS WHERE Precio BETWEEN 60 AND 120;

1.5

SELECT Nombre, Precio * 166.386 FROM ARTICULOS;
SELECT Nombre, Precio * 166.386 AS PrecioPtas FROM ARTICULOS,

1.6

SELECT AVG(Precio) FROM ARTICULOS;

1.7

SELECT AVG(Precio) FROM ARTICULOS WHERE Fabricante=2;

1.8

SELECT COUNT(*) FROM ARTICULOS WHERE Precio >=180;

1.9

SELECT Nombre,Precio FROM ARTICULOS WHERE Precio >= 180 ORDER BY Precio DESC, Nombre;

1.10

SELECT * FROM ARTICULOS, FABRICANTES WHERE ARTICULOS.Fabricante = FABRICANTES.Codigo;
SELECT * FROM ARTICULOS INNER JOIN FABRICANTES ON ARTICULOS.Fabricante = FABRICANTES.Codigo;




